function [] = fn_format_fig()

% set( gca                       , ...
%     'FontName'   , 'Helvetica' , ...
%     'FontSize'   , 12          , ...
%     'FontWeight' , 'bold'     );

set( gca                       , ...
    'FontName'   , 'Helvetica' , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'     );

set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 2         );

drawnow;
iptsetpref('ImshowBorder','tight');
set(gca, 'units', 'normalized'); 

end

